
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: dronwork
  password: user1

development:
  <<: *default
  database: web_screen_app_development


test:
  <<: *default
  database: web_screen_app_test


production:
  <<: *default
  database: web_screen_app_production
  username: web_screen_app
  password: <%= ENV['WEB_SCREEN_APP_DATABASE_PASSWORD'] %>
